/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use std::sync::Arc;

use crate::sync::engine::WebExtSyncEngine;
use crate::WebExtStorageStore;

// The collection name Desktop's Sync framework uses for `storage.sync`. Only
// used for telemetry labelling here (Desktop builds the collection URL itself).
const COLLECTION_NAME: &str = "extension-storage";

impl WebExtStorageStore {
    // Returns a bridged sync engine for this store.
    pub fn bridged_engine(self: Arc<Self>) -> Arc<WebExtStorageBridgedEngine> {
        let engine = Box::new(WebExtSyncEngine::new(&self.db, COLLECTION_NAME.into()));
        Arc::new(WebExtStorageBridgedEngine::new(engine))
    }
}

// The UniFFI-exposed `WebExtStorageBridgedEngine` (a thin newtype around
// `sync15::engine::BridgedEngineWrapper`) is generated by this macro, which
// removes the facade + BSO marshalling boilerplate. The wrapper drives the
// `WebExtSyncEngine` in the `engine` module (Desktop only uses the bridge, but
// implements the one unified `SyncEngine` trait like everyone else).
sync15::uniffi_bridged_engine!(WebExtStorageBridgedEngine);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::test::new_mem_thread_safe_storage_db;
    use crate::db::{get_meta, put_meta, StorageDb, ThreadSafeStorageDb};
    use crate::sync::engine::{LAST_SYNC_META_KEY, SYNC_ID_META_KEY};
    use anyhow::Result;
    use sync15::engine::BridgedEngineWrapper;

    // The sync-ID and reset semantics that used to live on the old
    // `BridgedEngine` trait now live on `BridgedEngineWrapper` (which drives our
    // `SyncEngine`), so we exercise them the same way Desktop does - through the
    // wrapper. Each engine holds a `Weak` to the shared db, so callers keep the
    // strong `Arc` alive and inspect DB state through it directly.
    fn wrapper(db: &Arc<ThreadSafeStorageDb>) -> BridgedEngineWrapper {
        BridgedEngineWrapper::new(Box::new(WebExtSyncEngine::new(db, COLLECTION_NAME.into())))
    }

    fn query_count(db: &StorageDb, table: &str) -> u32 {
        let conn = db.get_connection().expect("should retrieve connection");
        conn.query_row_and_then(&format!("SELECT COUNT(*) FROM {};", table), [], |row| {
            row.get::<_, u32>(0)
        })
        .expect("should work")
    }

    // Sets up mock data for the tests here.
    fn setup_mock_data(db: &Arc<ThreadSafeStorageDb>) -> Result<()> {
        {
            let shared = db.lock();
            let conn = shared.get_connection().expect("should retrieve connection");
            conn.execute(
                "INSERT INTO storage_sync_data (ext_id, data, sync_change_counter)
                    VALUES ('ext-a', 'invalid-json', 2)",
                [],
            )?;
            conn.execute(
                "INSERT INTO storage_sync_mirror (guid, ext_id, data)
                    VALUES ('guid', 'ext-a', '3')",
                [],
            )?;
        }
        // Seed a last-sync time directly - there's no public setter for it.
        {
            let shared = db.lock();
            let conn = shared.get_connection().expect("should retrieve connection");
            put_meta(conn, LAST_SYNC_META_KEY, &1i64)?;
        }

        let shared = db.lock();
        // and assert we wrote what we think we did.
        assert_eq!(query_count(&shared, "storage_sync_data"), 1);
        assert_eq!(query_count(&shared, "storage_sync_mirror"), 1);
        assert_eq!(query_count(&shared, "meta"), 1);
        Ok(())
    }

    // Assuming a DB setup with setup_mock_data, assert it was correctly reset.
    fn assert_reset(db: &Arc<ThreadSafeStorageDb>) -> Result<()> {
        // A reset never wipes data...
        let shared = db.lock();
        let conn = shared.get_connection().expect("should retrieve connection");
        assert_eq!(query_count(&shared, "storage_sync_data"), 1);

        // But did reset the change counter.
        let cc = conn.query_row_and_then(
            "SELECT sync_change_counter FROM storage_sync_data WHERE ext_id = 'ext-a';",
            [],
            |row| row.get::<_, u32>(0),
        )?;
        assert_eq!(cc, 1);
        // But did wipe the mirror...
        assert_eq!(query_count(&shared, "storage_sync_mirror"), 0);
        // And the last_sync should have been wiped.
        assert!(get_meta::<i64>(conn, LAST_SYNC_META_KEY)?.is_none());
        Ok(())
    }

    // Assuming a DB setup with setup_mock_data, assert it has not been reset.
    fn assert_not_reset(db: &Arc<ThreadSafeStorageDb>) -> Result<()> {
        let shared = db.lock();
        let conn = shared.get_connection().expect("should retrieve connection");
        assert_eq!(query_count(&shared, "storage_sync_data"), 1);
        let cc = conn.query_row_and_then(
            "SELECT sync_change_counter FROM storage_sync_data WHERE ext_id = 'ext-a';",
            [],
            |row| row.get::<_, u32>(0),
        )?;
        assert_eq!(cc, 2);
        assert_eq!(query_count(&shared, "storage_sync_mirror"), 1);
        // And the last_sync should remain.
        assert!(get_meta::<i64>(conn, LAST_SYNC_META_KEY)?.is_some());
        Ok(())
    }

    #[test]
    fn test_wipe() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;

        wrapper(&strong).wipe()?;

        let db = strong.lock();
        assert_eq!(query_count(&db, "storage_sync_data"), 0);
        assert_eq!(query_count(&db, "storage_sync_mirror"), 0);
        assert_eq!(query_count(&db, "meta"), 0);
        Ok(())
    }

    #[test]
    fn test_reset() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;
        {
            let db = strong.lock();
            let conn = db.get_connection()?;
            put_meta(conn, SYNC_ID_META_KEY, &"sync-id".to_string())?;
        }

        wrapper(&strong).reset()?;
        assert_reset(&strong)?;

        {
            let db = strong.lock();
            let conn = db.get_connection()?;
            // Only an explicit reset kills the sync-id, so check that here.
            assert_eq!(get_meta::<String>(conn, SYNC_ID_META_KEY)?, None);
        }

        Ok(())
    }

    #[test]
    fn test_ensure_missing_sync_id() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;

        assert_eq!(wrapper(&strong).sync_id()?, None);
        // We don't have a sync ID - so setting one should reset.
        wrapper(&strong).ensure_current_sync_id("new-id")?;
        // should have cause a reset.
        assert_reset(&strong)?;
        Ok(())
    }

    #[test]
    fn test_ensure_new_sync_id() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;

        {
            let db = strong.lock();
            let conn = db.get_connection()?;
            put_meta(conn, SYNC_ID_META_KEY, &"old-id".to_string())?;
        }

        assert_not_reset(&strong)?;
        assert_eq!(wrapper(&strong).sync_id()?, Some("old-id".to_string()));

        wrapper(&strong).ensure_current_sync_id("new-id")?;
        // should have cause a reset.
        assert_reset(&strong)?;
        // should have the new id.
        assert_eq!(wrapper(&strong).sync_id()?, Some("new-id".to_string()));
        Ok(())
    }

    #[test]
    fn test_ensure_same_sync_id() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;
        assert_not_reset(&strong)?;

        {
            let db = strong.lock();
            let conn = db.get_connection()?;
            put_meta(conn, SYNC_ID_META_KEY, &"sync-id".to_string())?;
        }

        wrapper(&strong).ensure_current_sync_id("sync-id")?;
        // should not have reset.
        assert_not_reset(&strong)?;
        Ok(())
    }

    #[test]
    fn test_reset_sync_id() -> Result<()> {
        let strong = new_mem_thread_safe_storage_db();
        setup_mock_data(&strong)?;

        {
            let db = strong.lock();
            let conn = db.get_connection()?;
            put_meta(conn, SYNC_ID_META_KEY, &"sync-id".to_string())?;
        }

        assert_eq!(wrapper(&strong).sync_id()?, Some("sync-id".to_string()));
        let new_id = wrapper(&strong).reset_sync_id()?;
        // should have cause a reset.
        assert_reset(&strong)?;
        assert_eq!(wrapper(&strong).sync_id()?, Some(new_id));
        Ok(())
    }
}
